[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mbstring', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.json', 'php82Extensions.bcmath', 'nodejs_20']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci']

[phases.build]
cmds = ['npm run build', 'php artisan config:cache', 'php artisan route:cache', 'php artisan view:cache']

[start]
cmd = 'bash railway-start.sh'
